### ISSUE TITLE
Issue with Origin Plug-in related, to Games bought on Epic and game installed through EAPlay

### ISSUE THREAD

**Issue by AlePeace** [FriendsOfGalaxy/galaxy-integration-origin#31]
**Describe the bug**
Good morning to everyone. In first place a want to congratulate with every creators of this plug-in, I ho you continuing to put effort in this cause. The second things is the problem that I face-of. The first is that a game bought through Epic Games Launcher, after dis installation, is still in the fog library, the second is that Star Wars: Jedi Fallen that I installed through EAPlay, won't show in the Fog library, is tath anything I do for resolve this problem??. I tried the tips that I found in the issue section of this plug-in, but nothing seems to help me. A suggestion is very appreciated, thanks a lot.

**Comment by FriendsOfGalaxy** [comment]
@AlePeace thanks for report.

Let me make sure I understand properly.

Problem 1:
- you've installed game from Epic
- you've uninstalled the game
- in Galaxy it still shows as installed with button "Play"

?

As far as I know, plugin have exactly oposite problem: so installed game from Epic won't show in Galaxy as installed at all. This issue will be fixed in upcoming plugin release. see #30 - I'm still struggling with some edge-cases, so it is not released yet.

Problem 2:
- you've installed Star Wars: Jedi Fallen through EAPlay,
- it is not shown in Galaxy as owned game

?

Please also attach your log files as stated in the issue template when you click "New issue".

**Comment by AlePeace** [comment]
I'm sorry for the log files, I attached it in this post and I'm sorry for my bad English. The analysis of the both problem are as you know. When the game from the Epic was installed also I have the same problem of the guy in the #30 issue, but then I uninstalled the game and it still shown as owned and playable.


[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/6142761/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
Ok, understand.
For problem 1 - it is a battlefront 2, right?

**Comment by AlePeace** [comment]
Yes right, I redeem it on the Epic then I have installed it in origin and yes I have uninstalled it from Eipic and Origin.

**Comment by FriendsOfGalaxy** [comment]
Hi @AlePeace 
I've released new Origin plugin version a week or two ago - could you please check if both problems are gone for you?

**Comment by AlePeace** [comment]
Hi @FriendsOfGalaxy , yes the problems are gone. Thanks, great job, I'll be waiting for the integrations with EA Desktop 😁👍

**Comment by FriendsOfGalaxy** [comment]
thanks for confirmation! Yeah, EA Desktop will be the next
