### ISSUE TITLE
[QUESTION] Any plans for a EA Desktop App integration script?

### ISSUE THREAD

**Issue by MancV21** [FriendsOfGalaxy/galaxy-integration-origin#32]
Hi. Seems EA are going to get rid of Origin and replace it for the EA Desktop App on PC. The app is in beta atm but it's being used for Xbox Game Pass users to allow EA Play usages on the XBGP for PC subscription. 

https://www.ea.com/ea-desktop-beta

Cheers.

**Comment by ShaunV2** [comment]
This is probably why GOG Galaxy isn't picking up any EA Play titles gotten through EA Desktop (Beta) App with Xbox Game Pass.  Also you can only run one client at a time, EA Desktop or Origin not both.   Lots of games are still missing from the EA Desktop app but that's only because it's still in beta.

**Comment by FriendsOfGalaxy** [comment]
Hi. We can add support for EA Desktop if they add support for URL protocol to install/launch games. Currently it doesn't work. For example you cannot trigger launching game from https://www.origin.com/game-library in the way it works for Origin.

**Comment by MancV21** [comment]
Ah OK. Thanks for letting me know.

**Comment by FriendsOfGalaxy** [comment]
Limited support was released - it no longer redirects to default browser when EA Desktop is installed. Launching games will probably start working out of the box when EA Desktop adds support for URL protocol.

**Comment by FriendsOfGalaxy** [comment]
I'm closing this for now - feel free to report other problems with EA Desktop in separate issue.

The way how the integration is displayed in Galaxy is out of the plugin scope. Report it to Galaxy instead.

**Comment by centrivical2** [comment]
Those of us that enjoy the Battlefield series whether its multiplayer or solo campaigns, but dislike the EA app & Origin launchers makes me question is there a way to bypass it?

My cousin gave me Battlefield Hardline over the Thanksgiving holiday and after installing it I was unable to play because he just gave me the disc, he didn't hold on to the case meaning there's no registration key number.
