### ISSUE TITLE
Games aren't launchable since stuck on 'Install' instead of 'Play'

### ISSUE THREAD

**Issue by OsoaGitHub** [FriendsOfGalaxy/galaxy-integration-origin#34]
**Describe the bug**
Games that I have installed are seen as Owned but not Installed and thus are not launchable as instead of 'Play' it is 'Install'. Clicking on Install just opens Origin and does nothing.

**Expected behavior**
I expect the plugin to allow me to open the game instead of 'Installing' it.

**Attached logs**
[Link](https://pastebin.com/HYKAxgtW)

**Comment by FriendsOfGalaxy** [comment]
Not much happend in logs, I would need more of them since you connect the plugin and then restart Galaxy.

From the first impression looks like https://github.com/gogcom/galaxy-integrations-python-api/issues/180 but I suppose it is after Galaxy restart, so already imported games are visible as owned, but Galaxy do not ask further for owned or installed games.

I have no reproduction in my environment.

**Comment by t0mtee** [comment]
Sorry for late response, since this issue I have moved to Playnite instead of GOG Galaxy.
